---
dependencies:
  - geerlingguy.java
  - geerlingguy.mysql

galaxy_info:
  author: geerlingguy
  description: SonarQube for Linux
  company: "Midwestern Mac, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - development
    - monitoring
    - sonar
    - sonarqube
    - codequality
    - scanner
