pipeline{
   agent any

   environment {
      ANSIBLE_CONFIG="${WORKSPACE}/deploy/ansible.cfg"
    }

      parameters {
      string(name: 'inventory', defaultValue: 'dev',  description: 'This is the inventory file for the environment to deploy configuration')
    }


   stages{

      stage("Initial cleanup") {
          steps {
            dir("${WORKSPACE}") {
              deleteDir()
            }
          }
        }

      stage('Checkout SCM') {
         steps{
            git branch: 'feature/jenkinspipeline-stages', url: 'https://github.com/Livingstone95/project-14-ci-cd.git'
         }
       }

      stage('Prepare Ansible For Execution') {
        steps {
          sh 'echo ${WORKSPACE}'          
        }
     }


      stage('Run Ansible') {
        steps {
          ansiblePlaybook become: true, colorized: true, credentialsId: 'Jenkins-ansible', disableHostKeyChecking: true, installation: 'ansible', inventory: 'inventory/${params.inventory_file}', playbook: 'playbooks/site.yml'
        }
      }

      stage('Clean Workspace after build'){
        steps{
          cleanWs()
        }
      }
   }
}  


