---
language: python
services: docker

env:
  global:
    - ROLE_NAME: sonar
  matrix:
    # LTS.
    - MOLECULE_DISTRO: centos7
      MOLECULE_DOCKER_COMMAND: /usr/lib/systemd/systemd
    - MOLECULE_DISTRO: ubuntu1604
      MOLECULE_DOCKER_COMMAND: /lib/systemd/systemd

    # Latest.
    - MOLECULE_DISTRO: centos7
      MOLECULE_DOCKER_COMMAND: /usr/lib/systemd/systemd
      MOLECULE_PLAYBOOK: playbook-latest.yml
    - MOLECULE_DISTRO: ubuntu1604
      MOLECULE_DOCKER_COMMAND: /lib/systemd/systemd
      MOLECULE_PLAYBOOK: playbook-latest.yml

    # Web Context.
    - MOLECULE_DISTRO: ubuntu1604
      MOLECULE_DOCKER_COMMAND: /lib/systemd/systemd
      MOLECULE_PLAYBOOK: playbook-web-context.yml

install:
  # Install test dependencies.
  - pip install molecule docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME geerlingguy.$ROLE_NAME
  - cd geerlingguy.$ROLE_NAME

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
